# Конфигурационный файл для плагина Herobrine

# Шанс появления NPC в процентах (от 0 до 1)
spawnChance: 0.2

# Расстояние, на котором может появиться NPC от игрока
spawnDistance: 10

# Имя скина для NPC
npcSkin: Steve

# Продолжительность события в секундах
eventDuration: 60

# Звук, который будет проигрываться при появлении NPC
npcStareSound: ENTITY_BLAZE_AMBIENT

# Список сообщений для ActionBar
actionBarMessages:
  - "Загадочный НПС появился рядом!"
  - "Остерегайтесь теней..."
  - "Что это было?!"


# plugin.getPluginConfig().getString("npcStareSound"));
# plugin.getPluginConfig().getStringList("actionBarMessages");