# by CUPcqkeee

skin: "Herobrine" # Имя скина для НПС
teleportSound: "ENTITY_ENDERMAN_TELEPORT" # Звук телепортации НПС
deathSound: "ENTITY_BLAZE_DEATH" # Звук при пропаже НПС
minSpawnDistance: 5 # Минимальное расстояние для спавна НПС (в блоках)
maxSpawnDistance: 7 # Максимальное расстояние для спавна НПС (в блоках)
durationEvent: 60 # В секундах | 60*20ticks - 2m
chanceSpawn: 20 # Процентное соотношение, то есть 20 = 20% ; 50 = 50% и т.д.
particle-type: REDSTONE # Вид партикла
actionBarMessages:
  - "Тестовое сообщение 1"
  - "Тестовое сообщение 2"
  - "Тестовое сообщение 3"
