name: HeroEvent
version: '${project.version}'
main: me.cupcqkeee.heroevent.HeroEvent
api-version: '1.20'
author: CUPcqkeee
commands:
  start:
    usage: /<command>
    description: start event
  reloadconfig:
    usage: /<command>
    description: reload configuration file
